[package]
name = "arrow_guide"
version = "0.1.0"
authors = ["Fernando Herrera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
doc-comment="0.3"
arrow = { git = "https://github.com/apache/arrow" }
